language: node_js

node_js:
  - '10'
  - '12'

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

script:
  - yarn run -s build
  - yarn run -s test:lint:quiet
  - yarn run -s test:style:quiet
  - yarn run -s test:jest
